providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"
PIP_NO_CACHE_DIR = "1"

[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python bot_curriculo.py"