providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python bot_curriculo.py"