providers = ["python"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.setup]
cmds = ["python -m pip install --upgrade pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "python bot_curriculo.py"